"use client"
import{useState}from 'react'
const cats=['All','Einladung','Absage','Anfrage','Beschwerde','Mitteilung','Glueckwunsch']
const fb=[
{category:'Einladung',title:'Party-Einladung',greeting:'Hallo Max,',body:'Ich mache am Samstag eine Party.\nIch lade euch alle herzlich ein.\nDie Party beginnt um 22 Uhr.\nDu musst unbedingt kommen!',closing:'Viele Gruesse,\nMax'},
{category:'Einladung',title:'Geburtstagseinladung',greeting:'Liebe Sarah,',body:'Am Sonntag ist mein Geburtstag!\nIch mache eine Feier zu Hause.\nDie Feier beginnt um 15 Uhr.',closing:'Herzliche Gruesse,\nMax'},
{category:'Absage',title:'Termin absagen',greeting:'Hallo Maria,',body:'Es tut mir leid, aber ich kann heute nicht kommen.\nIch bin krank.\nKann ich einen neuen Termin bekommen?',closing:'Mit freundlichen Gruessen,\nMax'},
{category:'Anfrage',title:'Anfrage Deutschkurs',greeting:'Sehr geehrte Damen und Herren,',body:'Ich interessiere mich fuer einen Deutschkurs.\nWann beginnt der naechste Kurs?\nWie viel kostet der Kurs?',closing:'Mit freundlichen Gruessen,\nMax Müller'},
{category:'Anfrage',title:'Anfrage Hotel',greeting:'Sehr geehrte Damen und Herren,',body:'Ich moechte ein Zimmer buchen.\nFuer zwei Personen, vom 10. bis 14. Juli.\nWas kostet das Zimmer pro Nacht?',closing:'Mit freundlichen Gruessen,\nMax Müller'},
{category:'Beschwerde',title:'Reklamation Amazon',greeting:'Sehr geehrte Damen und Herren,',body:'Ich habe bei Amazon Socken bestellt.\nSie waren zu klein.\nBitte senden Sie mir mein Geld zurueck.',closing:'Mit freundlichen Gruessen,\nMax Müller'},
{category:'Beschwerde',title:'Defekt in Wohnung',greeting:'Sehr geehrte Damen und Herren,',body:'In meiner Wohnung ist die Heizung kaputt.\nBitte reparieren Sie sie so schnell wie moeglich.',closing:'Mit freundlichen Gruessen,\nMax Müller'},
{category:'Mitteilung',title:'Adressaenderung',greeting:'Hallo,',body:'Ich bin umgezogen.\nMeine neue Adresse: Musterstrasse 5, 10115 Berlin.',closing:'Vielen Dank,\nMax Müller'},
{category:'Glueckwunsch',title:'Geburtstagswuensche',greeting:'Liebe Mutter,',body:'Herzlichen Glueckwunsch zum Geburtstag!\nIch wuensche dir alles Gute.\nIch rufe dich heute Abend an.',closing:'In Liebe,\nMax'},
]
export default function WritingSection({data}:{data?:any[]}){const templates=(data&&data.length>0)?data.map((d:any)=>d.fields):fb;const[filter,setFilter]=useState('All');const[open,setOpen]=useState<number|null>(null)
const filtered=filter==='All'?templates:templates.filter((t:any)=>t.category===filter)
return(<section id="writing" className="max-w-6xl mx-auto px-6 py-16 section-fade"><h2 className="text-3xl font-bold mb-2">Writing Templates</h2><p className="text-gray-500 mb-6">All TELC A1 writing scenarios</p><div className="flex flex-wrap gap-2 mb-8">{cats.map(c=>(<button key={c} onClick={()=>{setFilter(c);setOpen(null)}} className={`px-4 py-2 rounded-full text-sm font-medium border transition ${filter===c?'bg-blue-600 text-white':'bg-white text-gray-600 border-gray-200'}`}>{c}</button>))}</div><div className="space-y-3">{filtered.map((t:any,i:number)=>(<div key={i} className="border border-gray-200 rounded-2xl overflow-hidden"><button onClick={()=>setOpen(open===i?null:i)} className="w-full flex justify-between items-center px-6 py-4 bg-white hover:bg-gray-50 text-left"><div><span className="font-semibold text-gray-800">{t.title}</span><span className="ml-3 text-xs bg-blue-100 text-blue-700 px-2 py-1 rounded-full">{t.category}</span></div><span>{open===i?'-':'+ '}</span></button>{open===i&&(<div className="px-6 pb-6 bg-gray-50 border-t"><div className="bg-white rounded-xl p-5 mt-3 font-mono text-sm leading-7 whitespace-pre-line">{t.greeting+"\n\n"+t.body+"\n\n"+t.closing}</div></div>)}</div>))}</div><div className="mt-8 bg-yellow-50 border border-yellow-200 rounded-2xl p-5"><p className="font-bold text-yellow-800 mb-2">Writing Checklist</p><ul className="text-sm text-yellow-700 space-y-1 list-disc list-inside"><li>Start: Hallo / Liebe / Sehr geehrte Damen und Herren</li><li>Write 3-4 sentences minimum</li><li>Answer ALL task points</li><li>Close: Viele Gruesse / Mit freundlichen Gruessen + name</li><li>Verb always in position 2</li></ul></div></section>)}
